### ISSUE TITLE
link to xxhash

### ISSUE THREAD

**Issue by beckermr** [conda-forge/python-xxhash-feedstock#11]
It appears we already ship xxhash and the python package can link to it. Should we do that to make sure there is a consistent version installed? 

Nothing is actually broken right now FWIW.

**Comment by jakirkham** [comment]
I think PR ( https://github.com/conda-forge/python-xxhash-feedstock/pull/14 ) may have fixed this. Here are [the attached logs]( https://github.com/conda-forge/python-xxhash-feedstock/files/5038053/logs_193768.zip ).


cc @marcelotrevisani

**Comment by marcelotrevisani** [comment]
Yes, I think that PR fixed it
